# Generated by Django 4.2.7 on 2023-12-22 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_picture_comment',
        ),
        migrations.AddField(
            model_name='pet',
            name='nick',
            field=models.CharField(default='nick', max_length=255, unique=True, verbose_name='User of pet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blocker',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_user', to=settings.AUTH_USER_MODEL, verbose_name='User blocking another user'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_picture',
            field=models.URLField(null=True),
        ),
    ]
